### ISSUE TITLE
Update Recurring Tasks to the Next Future Date

### ISSUE THREAD

**Issue by darkBlueLemon** [ContriHUB/MinimalistTodoListV4#4]
### Expected behavior
When a recurring task is clicked, its due date should always update to the next date in the future, regardless of how far in the past the current due date is.

### Current behavior
When a user clicks on a recurring task that is overdue, the due date is simply updated to the next recurrence based on the current (past) due date, even if it results in another past date.

**Comment by RITIK-CHAUDHRY** [comment]
i have applied through contrihub please assign me the issue
@darkBlueLemon

**Comment by RITIK-CHAUDHRY** [comment]
@darkBlueLemon sir please review my PR also please add hacktoberfest label
